# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ralph < Formula
  desc "CLI tool to bootstrap and manage Claude Code harness configuration for your projects"
  homepage "https://github.com/thomas0124/ralph"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thomas0124/ralph/releases/download/v0.4.0/ralph_darwin_amd64.tar.gz"
      sha256 "f58e6ede68c40286f4ab61afbb43d8d67f0172c2866163d97ab9fbf6478844f9"

      define_method(:install) do
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thomas0124/ralph/releases/download/v0.4.0/ralph_darwin_arm64.tar.gz"
      sha256 "ccfdd7f831988b8bdda0c8bb719d34a32c5660eb4571daf8681fb220083fff88"

      define_method(:install) do
        bin.install "ralph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thomas0124/ralph/releases/download/v0.4.0/ralph_linux_amd64.tar.gz"
      sha256 "86b71229fd29312ba88edd030e7216d3aeb9494a104540df1d6ad6bf7534ade7"
      define_method(:install) do
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thomas0124/ralph/releases/download/v0.4.0/ralph_linux_arm64.tar.gz"
      sha256 "53d4ef1c96d27bea7c57c5651caaf58c2c1746a6a6878b1cf6eca8f34b23dcd0"
      define_method(:install) do
        bin.install "ralph"
      end
    end
  end

  test do
    system "#{bin}/ralph", "--version"
  end
end
