# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ralph < Formula
  desc "CLI tool to bootstrap and manage Claude Code harness configuration for your projects"
  homepage "https://github.com/thomas0124/ralph"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thomas0124/ralph/releases/download/v0.8.0/ralph_darwin_amd64.tar.gz"
      sha256 "2c3ead01cb73f04e3aa480cd1dfff8256590d121b6b7634e7d8b0ea8256f4146"

      define_method(:install) do
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thomas0124/ralph/releases/download/v0.8.0/ralph_darwin_arm64.tar.gz"
      sha256 "8995c9b82e1c53c6abeddf959711276798833553170d41426a336a0e1537d43d"

      define_method(:install) do
        bin.install "ralph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thomas0124/ralph/releases/download/v0.8.0/ralph_linux_amd64.tar.gz"
      sha256 "fbf255bbd62c98f1dc1d4f036b27d12d47bd402d54bafedd7e80e1bac7cc42e4"
      define_method(:install) do
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thomas0124/ralph/releases/download/v0.8.0/ralph_linux_arm64.tar.gz"
      sha256 "94754e510c3bd45bb17a0c82be9f02226fa8ded60e7cbae754aa396980966437"
      define_method(:install) do
        bin.install "ralph"
      end
    end
  end

  test do
    system "#{bin}/ralph", "--version"
  end
end
