# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ralph < Formula
  desc "CLI tool to bootstrap and manage Claude Code harness configuration for your projects"
  homepage "https://github.com/thomas0124/ralph"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thomas0124/ralph/releases/download/v0.3.0/ralph_darwin_amd64.tar.gz"
      sha256 "76a52069ea37bccc1af2763685ccabdd2602c696c81ea06154a47baa3b49d472"

      define_method(:install) do
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thomas0124/ralph/releases/download/v0.3.0/ralph_darwin_arm64.tar.gz"
      sha256 "bb3c9e9116e430e4b66ccdb40f35020e09ee4fb0ed68bb78129a6660857a6f9e"

      define_method(:install) do
        bin.install "ralph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thomas0124/ralph/releases/download/v0.3.0/ralph_linux_amd64.tar.gz"
      sha256 "9170bb7c0c4427a996cdddd9a6981c99648f5d7e27a73f1cc0c040c01fa31de4"
      define_method(:install) do
        bin.install "ralph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thomas0124/ralph/releases/download/v0.3.0/ralph_linux_arm64.tar.gz"
      sha256 "2c40c100aef954f3d24242f1650bd45e3319323a6d320c6068d8c6a9a58916b7"
      define_method(:install) do
        bin.install "ralph"
      end
    end
  end

  test do
    system "#{bin}/ralph", "--version"
  end
end
